const myConst = 5;
const myArray = [1,2,3,4,5];

myArray.push(4); // nao da erro
myArray = 5; // estora exception